daruma/app/urls.py
from django.urls import path
from . import views
from .views import PostDetail
from django.conf import settings
from django.conf.urls.static import static
 
app_name = 'app'
urlpatterns = [
   path('', views.index, name='index'),
   path('team', views.team, name='team'),
   path('blog', views.blog, name='blog'),
   path('post/<int:pk>', PostDetail.as_view(), name='post-detail'),
   path('privacy', views.privacy, name='privacy'),
   path('terms', views.terms, name='terms'),
   path('disclaimer', views.disclaimer, name='disclaimer'),
   path('sent', views.send_inquiry, name='sent'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

daruma/daruma/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

handler404 = 'app.views.handler404'

daruma/templates/app/blog.html
{% extends 'app/shared.html' %} {% block content %}
<section class="hero-short">
  <div class="flex-short">
    <div class="fluid-container">
      <div class="hero-text">
        <h1 data-aos="fade-up" data-aos-duration="1000" data-aos-offset="0">
          {{ blog.hero_title }}
        </h1>
        <p
          data-aos="fade-up"
          data-aos-delay="250"
          data-aos-duration="1000"
          data-aos-offset="0"
        >
          {{ blog.hero_subtitle }}
        </p>
      </div>
    </div>
  </div>
</section>

<section class="post-list white">
  <div class="fluid-container">
    {% if page_obj %} {% for post in page_obj %}
    <div class="post-item">
      <h1 class="post-title">
        <a href="{% url 'app:post-detail' post.pk %}">{{ post.title }}</a>
      </h1>

      <p class="post-signature">
        published {{ post.published_time }} by {{ post.author }}
      </p>

      <div class="post-excerpt">
        <p>{{ post.excerpt }}</p>
      </div>

      <a href="{% url 'app:post-detail' post.pk %}">Read post</a>
    </div>
    <hr />
    {% endfor %} {% else %}
    <p>No posts to display.</p>
    {% endif %}

    <div class="pagination">
      {% if page_obj.has_previous %}
      <a href="?page=1" class="pagination-item">&laquo; First</a>
      <a
        href="?page={{ page_obj.previous_page_number }}"
        class="pagination-item"
        >Prev</a
      >
      {% else %}
      <span class="pagination-item text-muted">&laquo; First</span>
      <span class="pagination-item text-muted">Prev</span>
      {% endif %}

      <span class="pagination-item current">
        {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
      </span>

      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}" class="pagination-item"
        >Next</a
      >
      <a href="?page={{ page_obj.paginator.num_pages }}" class="pagination-item"
        >Last &raquo;</a
      >
      {% else %}
      <span class="pagination-item text-muted">Next</span>
      <span class="pagination-item text-muted">Last &raquo;</span>
      {% endif %}
    </div>
  </div>
</section>
{% endblock %}

daruma/templates/app/footer.html
<section>
  <div class="short-flex">
    <div class="fluid-container">
      <div class="row">
        <div class="column-3">
          <strong>Site</strong>
          <hr />
          <ul>
            <li class="animated-link"><a href="{% url 'app:team' %}">Team</a></li>
            <li class="animated-link"><a href="{% url 'app:blog' %}">Blog</a></li>
            <li class="animated-link"><a href="{% url 'app:index' %}#contact">Contact</a></li>
          </ul>
        </div>
        <div class="column-3">
          <strong>Legal</strong>
          <hr />
          <ul>
            <li class="animated-link"><a href="{% url 'app:privacy' %}">Privacy policy</a></li>
            <li class="animated-link"><a href="{% url 'app:terms' %}">Terms of service</a></li>
            <li class="animated-link"><a href="{% url 'app:disclaimer' %}">Disclaimer</a></li>
          </ul>
        </div>
        <div class="column-3">
          {% if cdetail %}
          <strong>{{ cdetail.full_name }}</strong>
          <hr />
          <ul>
            <li>{{ cdetail.address_1 }}</li>
            <li>{{ cdetail.address_2 }}</li>
            <li>Tel. {{ cdetail.telephone }}</li>
          </ul>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  <div class="credit">
    <p>Based on <span class="animated-link"><a href="https://github.com/rzeczuchy/daruma" target="_blank" rel="noopener">Daruma</a></span> | Created by <span class="animated-link"><a href="https://github.com/rzeczuchy" target="_blank" rel="noopener">Michal</a></span></p>
  </div>
</section>

daruma/templates/app/header.html
<nav class="responsive-nav">
  <div class="container">
      <a href="{% url 'app:index' %}" class="brand">{{ cdetail.name }}</a>
      <input type="checkbox" class="navbar-toggle" id="navbar-toggle">
      <label for="navbar-toggle" class="hamburger">
        <span class="hamburger-icon"></span>
      </label>
      <ul class="navbar">
        <li class="navbar-item underline-link"><a href="{% url 'app:team' %}">Team</a></li>
        <li class="navbar-item underline-link"><a href="{% url 'app:blog' %}">Blog</a></li>
        <li class="navbar-item underline-link"><a href="{% url 'app:index' %}#contact">Contact</a></li>
      </ul>
  </div>
</nav>

daruma/templates/app/index.html
{% extends 'app/shared.html' %} {% block content %}
<section class="hero">
  <div class="flex">
    <div class="fluid-container">
      <div class="hero-text">
        <h1 data-aos="fade-up" data-aos-duration="1000" data-aos-offset="0">
          {{ home.hero_title }}
        </h1>
        <p
          data-aos="fade-up"
          data-aos-delay="250"
          data-aos-duration="1000"
          data-aos-offset="0"
        >
          {{ home.hero_subtitle }}
        </p>
      </div>
    </div>
  </div>

  <div class="anchor-link">
    <a href="#intro"><i class="arrow-down"></i></a>
  </div>
</section>

<section id="intro" class="primary">
  <div class="flex">
    <div class="fluid-container">
      <h2>{{ home.intro_title }}</h2>
      {{ home.intro_content|safe }}
    </div>
  </div>
</section>

<section class="background-image">
  <div class="flex">
    <div class="fluid-container">
      <h2>
      {{ home.logos_title }}
      </h2>
      {% if plogos %}
      <div class="row">
        {% for logo in plogos %}
        <div class="column-4">
          <div class="logo">
            <img src="{{ logo.image.url }}" alt="Logo" />
          </div>
        </div>
        {% if forloop.counter|divisibleby:4 %}
      </div>
      <div class="row">{% endif %} {% endfor %}</div>
      {% endif %}
    </div>
  </div>
</section>

<section id="team" class="white">
  <div class="flex">
    <div class="fluid-container">
      <h2>
        {{ home.team_title }}
      </h2>

      {% if tmembers %}
      <div class="row">
        {% for person in tmembers %}
        <div class="column-3">
          <div class="card">
            <img src="{{ person.portrait.url }}" alt="Portrait" />
            <div class="card-content">
              <h2 class="name">{{ person.name }}</h2>
              <p class="title">{{ person.title }}</p>
              <p>{{ person.description }}</p>
              <p>{{ person.email }}</p>
            </div>
          </div>
        </div>
        {% if forloop.counter|divisibleby:3 %}
      </div>
      <div class="row">{% endif %} {% endfor %}</div>

      <div class="animated-link center-content">
        <a href="{% url 'app:team' %}">{{ home.team_link_text }}</a>
      </div>
      {% endif %}
    </div>
  </div>
</section>

<section id="contact" class="contact-form primary">
  <div class="flex">
    <div class="fluid-container">
      <h2>
        {{ home.contact_title }}
      </h2>
      <div class="form-container">
        <form action="{% url 'app:sent' %}" method="post">
          {% csrf_token %} {{ cform.as_p }}
          <input class="button" type="submit" value="Submit" />
        </form>
      </div>
    </div>
  </div>
</section>

<section class="background-image">
  <div class="flex-short"></div>
</section>
{% endblock %}

daruma/templates/app/post.html
{% extends 'app/shared.html' %} {% block content %}
<section class="hero-short">
  <div class="flex-short">
    <div class="fluid-container">
      <div class="hero-text">
        <h1 data-aos="fade-up" data-aos-duration="1000" data-aos-offset="0">
          {{ post.title }}
        </h1>
        <p
          data-aos="fade-up"
          data-aos-delay="250"
          data-aos-duration="1000"
          data-aos-offset="0"
        >
          {{ post.published_time }} by {{ post.author }}
        </p>
      </div>
    </div>
  </div>
</section>

<section class="white">
  <div class="fluid-container">
    <div class="post-detail">
      <h1 class="post-title">{{ post.title }}</h1>

      <p class="post-signature">
        {{ post.published_time }} by {{ post.author }}
      </p>

      <div class="post-content">
        <p>{{ post.main_content|safe }}</p>
      </div>

      <a href="{% url 'app:blog' %}">Back to Blog</a>
    </div>
  </div>
</section>
{% endblock %}

daruma/templates/app/shared.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Noto+Serif:ital,wght@0,400;0,700;1,400;1,700&display=swap"
      rel="stylesheet"
    />
    <!-- Animate on Scroll CSS -->
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <!-- Cookie Consent CSS -->
    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.css"
    />
    <!-- Styles -->
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'app/css/style.css' %}"
    />
    <!-- Favicon -->
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'app/favicon.ico' %}"
    />
    <!-- SEO -->
    {% if pdescription %}
    <meta name="description" content="{{ pdescription }}" />
    {% endif %}
    <!-- Title -->
    <title>
      {% if ptitle %} {{ ptitle }} {% else %} Page title {% endif %}
    </title>
  </head>
  <body>
    <header>{% include "app/header.html"%}</header>

    <main>{% block content %} {% endblock %}</main>

    <footer>{% include "app/footer.html" %}</footer>

    <!-- Animate on Scroll scripts -->
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
      AOS.init({
        once: true,
        duration: 1000,
      });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js"></script>
    <script>
      window.cookieconsent.initialise({
        palette: {
          popup: {
            background: "#005336",
            text: "#ffffff",
          },
          button: {
            background: "transparent",
            text: "#96b742",
            border: "#96b742",
          },
        },
        position: "bottom-left",
        content: {
          message:
            "This website uses cookies to ensure you get the best experience.",
          dismiss: "Got it!",
          link: "What are cookies?",
        },
      });
    </script>
  </body>
</html>

daruma/templates/app/simple.html
{% extends 'app/shared.html' %} {% block content %}
<section class="hero-short">
  <div class="flex-short">
    <div class="fluid-container">
      <div class="hero-text">
        <h1 data-aos="fade-up" data-aos-duration="1000" data-aos-offset="0">
          {{ pobject.title }}
        </h1>
        <p
          data-aos="fade-up"
          data-aos-delay="250"
          data-aos-duration="1000"
          data-aos-offset="0"
        >
          {{ pobject.subtitle }}
        </p>
      </div>
    </div>
  </div>
</section>

<section class="white">
    <div class="fluid-container">
      <div class="post-detail">
        <div class="post-content">
          <p>{{ pobject.content|safe }}</p>
        </div>
        <a href="{% url 'app:index' %}">Back to Home</a>
      </div>
    </div>
  </section>
{% endblock %}

daruma/templates/app/subpage.html
{% extends 'app/shared.html' %} {% block content %}
<section class="hero-short">
  <div class="flex-short">
    <div class="fluid-container">
      <div class="hero-text">
        <h1 data-aos="fade-up" data-aos-duration="1000" data-aos-offset="0">
          {{ pobject.hero_title }}
        </h1>
        <p
          data-aos="fade-up"
          data-aos-delay="250"
          data-aos-duration="1000"
          data-aos-offset="0"
        >
          {{ pobject.hero_subtitle }}
        </p>
      </div>
    </div>
  </div>
</section>

<section class="white">
    <div class="fluid-container">
      <div class="post-detail">
        <div class="post-content">
          <p>{{ pobject.content|safe }}</p>
        </div>
        <a href="{% url 'app:index' %}">Back to Home</a>
      </div>
    </div>
  </section>
{% endblock %}

daruma/templates/app/team.html
{% extends 'app/shared.html' %} {% block content %}
<section class="hero-short">
  <div class="flex-short">
    <div class="fluid-container">
      <div class="hero-text">
        <h1 data-aos="fade-up" data-aos-duration="1000" data-aos-offset="0">
          {{ team.hero_title }}
        </h1>
        <p
          data-aos="fade-up"
          data-aos-delay="250"
          data-aos-duration="1000"
          data-aos-offset="0"
        >
          {{ team.hero_subtitle }}
        </p>
      </div>
    </div>
  </div>
</section>

<section class="white">
  <div class="flex">
    <div class="fluid-container">
      <h2>{{ team.team_title }}</h2>

      {% if tmembers %}
      <div class="row">
        {% for person in tmembers %}
        <div class="column-3">
          <div class="card">
            <img src="{{ person.portrait.url }}" alt="Jane" />
            <div class="card-content">
              <h2 class="name">{{ person.name }}</h2>
              <p class="title">{{ person.title }}</p>
              <p>{{ person.description }}</p>
              <p>{{ person.email }}</p>
            </div>
          </div>
        </div>
        {% if forloop.counter|divisibleby:3 %}
      </div>

      <div class="row">{% endif %} {% endfor %}</div>
      {% endif %}
    </div>
  </div>
</section>
{% endblock %}

daruma/templates/app/thanks.html
{% extends 'app/shared.html' %} {% block content %}
<section>
  <div class="fluid-container"></div>
</section>

<section class="white center-content">
  <div class="flex">
    <div class="fluid-container">
      <h1>Thank you!</h1>
      <p>
        Your inquiry has been sent to the team, and we will get back to you shortly!
      </p>
    </div>
  </div>
</section>

{% endblock %}